services:
  # 1. Banco de Dados para o Zabbix
  zabbix-db:
    image: postgres:15-alpine
    container_name: zabbix-db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${ZABBIX_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ZABBIX_POSTGRES_PASSWORD}
      - POSTGRES_DB=${ZABBIX_POSTGRES_DB}
    volumes:
      - zabbix_db_data:/var/lib/postgresql/data
    networks:
      - stack_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Servidor Zabbix
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-7.0-latest
    container_name: zabbix-server
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "11051:10051" # bind local
    depends_on:
      zabbix-db:
        condition: service_healthy
    environment:
      DB_SERVER_HOST: zabbix-db
      DB_SERVER_PORT: 5432
      POSTGRES_USER: ${ZABBIX_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ZABBIX_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ZABBIX_POSTGRES_DB}
      TZ: America/Sao_Paulo
    env_file:
      - .env
    networks:
      - stack_network
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1.5G
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "zabbix_server", "-V"]
      interval: 30s
      timeout: 10s
      retries: 5

  # 3. Interface Web do Zabbix
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.0-latest
    container_name: zabbix-web
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "18081:8080" # Acesso ao Zabbix Frontend (reverse proxy)
    depends_on:
      zabbix-server:
        condition: service_healthy
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      DB_SERVER_HOST: zabbix-db
      DB_SERVER_PORT: 5432
      POSTGRES_USER: ${ZABBIX_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ZABBIX_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ZABBIX_POSTGRES_DB}
      TZ: America/Sao_Paulo
    env_file:
      - .env
    networks:
      - stack_network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  zabbix_db_data:

networks:
  stack_network:
    external: true
